name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcrun xctrace list devices
          xcodebuild build-for-testing -scheme "Searching" -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" -project Searching.xcodeproj
      - name: Test
        run: |
          xcodebuild test-without-building -scheme "Searching" -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" -project Searching.xcodeproj
